# Generated by Django 5.2.1 on 2025-06-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_usersettings_usersetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='roles',
            new_name='role',
        ),
    ]
