# Generated by Django 5.2.1 on 2025-06-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_workgroup_alter_membership_group_delete_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgroup',
            name='title',
            field=models.CharField(default='Workgroup', max_length=128),
        ),
        migrations.AlterField(
            model_name='workgroup',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
