# Generated by Django 5.2.1 on 2025-06-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_workgroup_title_alter_workgroup_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workgroup',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='workgroups',
            field=models.ManyToManyField(blank=True, through='api.Membership', to='api.workgroup'),
        ),
    ]
