# Generated by Django 5.2.1 on 2025-06-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_note_group_alter_tag_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('green', 'Green'), ('white', 'White'), ('black', 'Black')], max_length=7),
        ),
    ]
