# Generated by Django 5.2.1 on 2025-06-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('red-10', 'Red'), ('light-green', 'Green'), ('light-blue-6', 'Blue'), ('yellow', 'Yellow'), ('purple-9', 'Purple'), ('orange', 'Orange'), ('white', 'White'), ('grey', 'Grey'), ('black', 'Black')], max_length=32),
        ),
    ]
