# Generated by Django 5.2.1 on 2025-06-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('light-green', 'Green'), ('light-blue', 'Blue'), ('yellow', 'Yellow'), ('purple', 'Purple'), ('orange', 'Orange'), ('white', 'White'), ('grey', 'Grey')], max_length=32),
        ),
    ]
