# Generated by Django 5.2.1 on 2025-06-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_note_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='label',
        ),
        migrations.AlterField(
            model_name='note',
            name='lastEdited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
